# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/syncmaster',
                'doc_host': 'https://conorkeogh.github.io',
                'git_url': 'https://github.com/conorkeogh/syncmaster',
                'lib_path': 'syncmaster'},
  'syms': {'syncmaster.core': {'syncmaster.core.foo': ('core.html#foo', 'syncmaster/core.py')}}}
